name: polymer_dart_samples
description: Port of https://github.com/PolymerLabs/polymer-snippets
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  #core_elements: ">=0.6.0 <0.7.0"
  web_components: ^0.12.0
  polymer: ^0.17.0
transformers:
- web_components:
    entry_points:
    - web/basics/binding_to_a_field/index.html
   # - web/basics/binding_to_a_complex_object/index.html
   # - web/basics/binding_to_a_map/index.html
   # - web/basics/binding_to_a_native_html_element/index.html
   # - web/basics/binding_to_a_style/index.html
   # - web/basics/finding_shadow_dom_elements/index.html
   # - web/basics/using_bind_to_create_a_single_template_instance/index.html
   # - web/basics/creating_a_one_time_binding/index.html
   # - web/basics/using_a_computed_property/index.html

   # - web/control_flow/conditionally_hiding_an_element/index.html
   # - web/control_flow/getting_the_iteration_index_when_looping_over_a_collection/index.html
   # - web/control_flow/looping_over_a_collection_using_iterative_templates/index.html
   # - web/control_flow/using_conditional_templates/index.html
   # - web/control_flow/using_template_repeat_with_a_table_row_or_an_option/index.html

   # - web/insertion_points/creating_an_insertion_point_using_the_control_tag/index.html
   # - web/insertion_points/creating_insertion_points_using_the_select_attribute/index.html
   # - web/insertion_points/accessing_the_dom_inside_a_content_tag/index.html
   # - web/insertion_points/retrieving_the_insertion_points_for_distributed_nodes/index.html

   # - web/inheritance/extending_a_polymer_element/index.html
   # - web/inheritance/overriding_an_inherited_method/index.html

   # - web/observing_changes/observing_changes_to_element_fields/index.html
   # - web/observing_changes/observing_changes_to_light_dom_children/index.html
   # - web/observing_changes/watching_for_changes_to_a_nested_object/index.html

   # - web/forms/binding_a_boolean_field_to_a_checkbox/index.html
   # - web/forms/binding_to_a_text_input/index.html
   # - web/forms/binding_to_a_textarea/index.html
   # - web/forms/implementing_simple_autocompletion/index.html
   # - web/forms/implementing_simple_validation/index.html
   # - web/forms/selecting_one_item_using_radio_buttons/index.html
   # - web/forms/selecting_many_items_using_checkboxes/index.html

   # - web/events/using_custom_events/index.html

   # - web/styling_elements/applying_styles_by_piercing_shadow_dom_boundaries/index.html
   # - web/styling_elements/defining_styles_inside_a_polymer_element/index.html
   # - web/styling_elements/programmatically_changing_the_styles_of_an_element/index.html
   # - web/styling_elements/styling_distributed_nodes/index.html
   # - web/styling_elements/using_host_context_to_theme_an_element/index.html
   # - web/styling_elements/using_host_with_a_css_selector/index.html
   # - web/styling_elements/using_host_with_pseudo_classes/index.html

   # - web/layout_attributes/nesting_flex_layouts/index.html
   # - web/layout_attributes/using_flex/index.html
   # - web/layout_attributes/using_layout_attributes/index.html

   # - web/core_elements/core_toolbar/adding_a_menu_button/index.html
   # - web/core_elements/core_toolbar/adding_button_rows/index.html
   # - web/core_elements/core_toolbar/changing_the_toolbar_size/index.html
   # - web/core_elements/core_toolbar/using_core_toolbar/index.html
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
dependency_overrides:
  polymer:
    git:
      ref: 0.17-0-dev-interop-reverse
      url: https://github.com/dart-lang/polymer-dart.git
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git
